name: PlantStress
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - archspec=0.2.5=pyhd8ed1ab_0
  - boltons=25.0.0=pyhd8ed1ab_0
  - brotli-python=1.2.0=py312hdb49522_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda=25.11.0=py312h7900ff3_0
  - conda-libmamba-solver=25.11.0=pyhd8ed1ab_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.12.0=pyhd8ed1ab_0
  - cpp-expected=1.3.1=h171cf75_0
  - distro=1.9.0=pyhd8ed1ab_1
  - fmt=12.0.0=h2b0788b_0
  - frozendict=2.4.7=py312h4c3975b_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h7900ff3_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libarchive=3.8.2=gpl_h7be2006_100
  - libcurl=8.17.0=h4e3cde8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgomp=15.2.0=he0feb66_15
  - libiconv=1.18=h3b78370_2
  - liblzma=5.8.1=hb9d3cd8_2
  - libmamba=2.4.0=hed7d790_1
  - libmambapy=2.4.0=py312h17091a9_1
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsolv=0.7.35=h9463b59_0
  - libsqlite=3.51.1=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libuuid=2.41.2=h5347b49_1
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h031cc0b_0
  - libxml2-16=2.15.1=hf2a90c1_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - mamba=2.4.0=h7ae174a_1
  - menuinst=2.4.1=py312h7900ff3_0
  - msgpack-python=1.1.2=py312hd9148b4_1
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhf9edf01_1
  - pybind11-abi=11=hc364b38_1
  - pycosat=0.6.6=py312h4c3975b_3
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=hd63d673_1_cpython
  - python_abi=3.12=8_cp312
  - readline=8.2=h8c095d6_2
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - requests=2.32.5=pyhd8ed1ab_0
  - ruamel.yaml=0.18.16=py312h4c3975b_0
  - ruamel.yaml.clib=0.2.14=py312h4c3975b_0
  - setuptools=80.9.0=pyhff2d567_0
  - simdjson=4.2.2=hb700be7_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.1=pyhd8ed1ab_1
  - truststore=0.10.3=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml-cpp=0.8.0=h3f2d84a_0
  - zstandard=0.25.0=py312h5253ce2_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - numpy==2.4.1
      - pandas==3.0.0
      - pillow==12.1.0
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - seaborn==0.13.2
      - six==1.17.0
prefix: /home/youngmin/miniforge3new
